version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:
    external: true